version: "3.9"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: "TestDB"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "peace"
    volumes:
      - ./ddl/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./dml/insert.sql:/docker-entrypoint-initdb.d/insert.sql
    ports:
      - "5432:5432"
